---
ansible:
  playbook: playbook.yml
  timeout: 30

molecule:
  test:
    sequence:
      - destroy
      - syntax
      - create
      - converge
      - verify
#      - idempotence
  ignore_paths:
    - .git
    - .vagrant
    - .molecule
    - .env
    - .virtualenv

driver:
  name: docker

docker:
  containers:
  - name: zabbix-agent-centos
    ansible_groups:
      - group1
    image: milcom/centos7-systemd
    image_version: latest
    privileged: True
  - name: zabbix-agent-debian
    ansible_groups:
      - group2
    image: maint/debian-systemd
    image_version: latest
    privileged: True
  - name: zabbix-agent-ubuntu
    ansible_groups:
      - group2
    image: solita/ubuntu-systemd
    image_version: latest
    privileged: True
  - name: zabbix-agent-mint
    ansible_groups:
      - group2
    image: vcatechnology/linux-mint
    image_version: latest
    privileged: True
#  - name: zabbix-agent-suse
#    ansible_groups:
#      - group3
#    image: reszelaz/leap-systemd
#    image_version: latest
#    privileged: True
#    environment:
#      docker: container

verifier:
  name: testinfra
